### ISSUE TITLE
How to change max plots per player?

### ISSUE THREAD

**Issue by XiangZhao969** [wiez/MyPlot#65]
Here is my config for world plot, i set it to 6 but players can have only 2 plots
---
MaxPlotsPerPlayer: 6
ClaimPrice: 5000
ClearPrice: 200
DisposePrice: 200
ResetPrice: 200
RestrictEntityMovement: true
...

**Comment by Driesboy** [comment]
Set it to 6 in world config and config

**Comment by wiez** [comment]
Because most server owners who use this plugin have multiple permission groups that need different amount of plots, we changed the way you change this setting. It's managed through permissions now, so you'll need to change the plugin.yml file or use a permission plugin. Look  for the permission group `myplot.claimplots` in the wiki for more information
